### ISSUE TITLE
CreateRemoteThread failed, DLL failing to inject into game executable at last possible moment.

### ISSUE THREAD

**Issue by wearrrrr** [crwn1337/wine_injector#4]
Hello! I've been trying to use wine_injector, and I've stumbled across an issue which has prevented me from injecting DLLs into a process, CreateRemoteThread seems to reliably fail every time I try to use it, This is how I am launching wine_injector

```
WINEDEBUG=-all LANG=ja_JP.utf8 wine ../../wine_injector/wine_injector.exe /home/wearr/Documents/Coding/wine_injector/inject.dll /home/wearr/Documents/Coding/touhou_6_reverse_engineering/game/th06.exe
```

and here is the example DLL I am using.

```C
#include <windows.h>

BOOL APIENTRY DllMain(HINSTANCE hInstDLL, DWORD fdwReason, LPVOID lpvReserved)
{
    switch (fdwReason)
    {
        case DLL_PROCESS_ATTACH:
            MessageBoxA(NULL, "Hello From The Injected DLL", "Injected !", MB_OK | MB_ICONINFORMATION);
            break;

        case DLL_THREAD_ATTACH:
            MessageBoxA(NULL, "Hello From The Injected DLL", "Injected !", MB_OK | MB_ICONINFORMATION);
            break;

        case DLL_THREAD_DETACH:
            MessageBoxA(NULL, "Hello Again From The Injected DLL", "Injected !", MB_OK | MB_ICONINFORMATION);
            break;

        case DLL_PROCESS_DETACH:
            MessageBoxA(NULL, "Hello Again From The Injected DLL", "Injected !", MB_OK | MB_ICONINFORMATION);
            break;
    }

    return TRUE;
}
```

Thank you for reading! The DLL seems valid, and the games are obviously running in the same wineprefix, so I'm not sure why it's failing.

**Comment by wearrrrr** [comment]
Interestingly, I'm getting ERROR_INVALID_PARAMETER, which I found by adding `printf("%d", GetLastError());` below the "CreateRemoteThread Failed" printf.

**Comment by wearrrrr** [comment]
I should also note that I have tried compiling both with i686-w64-mingw32-gcc and  x86_64-w64-mingw32-gcc

**Comment by crwn1337** [comment]
It's kind of hard to tell what's wrong, you can try to build the dll statically and see if that helps, but ERROR_INVALID_PARAMETER indicates that there might be something wrong with the arguments being passed, can you uncomment [these lines](https://github.com/crwn1337/wine_injector/blob/818357c90685a66c1df213a335a7e027f48e3638/main.c#L31-L33) and tell me the output?

**Comment by wearrrrr** [comment]
Finally got around to being able to try this, here is the output of those lines

```
dll: /home/wearr/Documents/Coding/wine_injector/vpatch.dll
exe: /home/wearr/Documents/Coding/touhou_6_reverse_engineering/game/th06.exe
args: /home/wearr/Documents/Coding/touhou_6_reverse_engineering/game/th06.exe
```

seems correct, I am targeting a 32 bit game with a 32 bit dll, this should work but seemingly its not.

**Comment by crwn1337** [comment]
I currently don't have access to a linux system, but can you try running it as:
`wine wine_injector.exe Z:/home/wearr/Documents/Coding/wine_injector/vpatch.dll Z:/home/wearr/Documents/Coding/touhou_6_reverse_engineering/game/th06.exe`
or if that still doesn't work, you could try moving all of the files to your wine prefix folder (ex: C:/th6 and C:/dlls) and doing:
`wine wine_injector.exe C:/dlls/vpatch.dll C:/th6/game/th06.exe` or something similar.

**Comment by yukiruichi** [comment]
Hi, excuse me. I'm having the same issue, not the same cause but rather an exclamation mark is causing an issue.

Ex:
`WINEDEBUG=-all wine wine_injector.exe "Z://home/user/Downloads/wine_injector/bin/test.dll" "Z://home/user/Tester/komi/game!.exe"`

Output:
`bash: !.exe: event not found`

Unfortunately, I can't remove the exclamation mark from the exe's file name as it will crash and not run.
