### ISSUE TITLE
error when injecting modding dll inside a known chinese gacha game

### ISSUE THREAD

**Issue by yapudjus** [crwn1337/wine_injector#5]
i won't say the name of the game since they are really active on tracing back modders.
i'm attempting to inject a dll i got from https://github.com/kindawindytoday/Minty-Releases
i use this command and wait for the game to start to press enter:
`c:\Program Files\------ --------\G------ ------- game>wine_injector.exe minty.dll G----------ct.exe`
but i get this [backtrace.txt](https://github.com/crwn1337/wine_injector/files/14397208/backtrace.txt)
i have also opened an issue on their discord but... yeah they are slow
https://discord.gg/kindawindytoday
https://discord.com/channels/1062311282558107719/1211357806389760030

thanks for the program, if you need any info i can provide them

**Comment by crwn1337** [comment]
from the looks of it, the launcher of that "mod" works exactly the same way as this project, can you not use the launcher with wine? this is a bit out of the scope of this projects unfortunately so you'll need to contact the developers of that "mod".

<details>
  <summary>diff</summary>

![image](https://github.com/crwn1337/wine_injector/assets/38888474/d76b4b28-278f-45f7-b148-88f847cc1619)
https://github.com/crwn1337/wine_injector/blob/818357c90685a66c1df213a335a7e027f48e3638/main.c#L35


![image](https://github.com/crwn1337/wine_injector/assets/38888474/c02100e7-d1de-455f-9838-57eaadeac85f)
https://github.com/crwn1337/wine_injector/blob/818357c90685a66c1df213a335a7e027f48e3638/main.c#L46-L61

</details>
